"""v1 : Initial migration for PDFDocument and ChatHistory models

Revision ID: 060cc7c18d13
Revises: 
Create Date: 2025-08-09 16:32:18.783004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '060cc7c18d13'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_documents',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('pinecone_namespace', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_pdf_documents_uuid'), 'pdf_documents', ['uuid'], unique=True)
    op.create_table('chat_history',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('pdf_uuid', sa.String(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pdf_uuid'], ['pdf_documents.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_chat_history_uuid'), 'chat_history', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_history_uuid'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_pdf_documents_uuid'), table_name='pdf_documents')
    op.drop_table('pdf_documents')
    # ### end Alembic commands ###
