"""Add detailed YouTube video metadata fields

Revision ID: 71f39e3d5b90
Revises: 68c37be23ee5
Create Date: 2025-08-11 02:02:10.498045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71f39e3d5b90'
down_revision: Union[str, None] = '68c37be23ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_summaries', sa.Column('video_id', sa.String(), nullable=True))
    op.add_column('youtube_summaries', sa.Column('channel_id', sa.String(), nullable=True))
    op.add_column('youtube_summaries', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('youtube_summaries', sa.Column('published_at', sa.String(), nullable=True))
    op.add_column('youtube_summaries', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('youtube_summaries', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('youtube_summaries', sa.Column('like_count', sa.Integer(), nullable=True))
    op.add_column('youtube_summaries', sa.Column('comment_count', sa.Integer(), nullable=True))
    op.add_column('youtube_summaries', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('youtube_summaries', sa.Column('category_id', sa.String(), nullable=True))
    op.add_column('youtube_summaries', sa.Column('thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_summaries', 'thumbnail_url')
    op.drop_column('youtube_summaries', 'category_id')
    op.drop_column('youtube_summaries', 'tags')
    op.drop_column('youtube_summaries', 'comment_count')
    op.drop_column('youtube_summaries', 'like_count')
    op.drop_column('youtube_summaries', 'view_count')
    op.drop_column('youtube_summaries', 'duration')
    op.drop_column('youtube_summaries', 'published_at')
    op.drop_column('youtube_summaries', 'description')
    op.drop_column('youtube_summaries', 'channel_id')
    op.drop_column('youtube_summaries', 'video_id')
    # ### end Alembic commands ###
