"""add_vector_db_type_and_rename_namespace

Revision ID: ae6ffd1bb40e
Revises: eae19936d15e
Create Date: 2025-08-13 02:26:25.227165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae6ffd1bb40e'
down_revision: Union[str, None] = 'eae19936d15e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('vector_db_type', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('namespace', sa.String(), nullable=True))
    op.drop_column('documents', 'pinecone_namespace')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('pinecone_namespace', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('documents', 'namespace')
    op.drop_column('documents', 'vector_db_type')
    # ### end Alembic commands ###
