"""Add youtube_summaries table

Revision ID: ebefbae047fa
Revises: 060cc7c18d13
Create Date: 2025-08-10 06:19:57.918141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebefbae047fa'
down_revision: Union[str, None] = '060cc7c18d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_summaries',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_youtube_summaries_uuid'), 'youtube_summaries', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_youtube_summaries_uuid'), table_name='youtube_summaries')
    op.drop_table('youtube_summaries')
    # ### end Alembic commands ###
